### ISSUE TITLE
Build is failed

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [simpligility/android-ndk-maven-plugin#20]
As for now `com.simpligility.maven.plugins:android-ndk-maven-plugin` has version `1.1.3-SNAPSHOT` while all test projects relates to version `1.1.1-SNAPSHOT`
After changing version in root `pom.xml` from `1.1.3-SNAPSHOT` to `1.1.1-SNAPSHOT` I have got an error message:
```
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-ndk-maven-plugin:1.1.1-SNAPSHOT:ndk-build (default-ndk-build) on project native-
code: Failure during build: ANDROID-040-001: Could not execute: Command = cmd.exe /X /C "c:\Users\User\AppData\Local\Android\sdk\ndk-bundle\ndk-build.
cmd "APP_ABI=x86 armeabi armeabi-v7a mips" -C D:\workspace\android-ndk-maven-plugin\src\test\projects\native\native-code NDK_LIBS_OUT=D:\workspace\and
roid-ndk-maven-plugin\src\test\projects\native\native-code\target\ndk-libs NDK_OUT=D:\workspace\android-ndk-maven-plugin\src\test\projects\native\nati
ve-code\target\obj V=1 -B all", Result = 2 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.simpligility.maven.plugins:android-ndk-maven-plugin:1.1.1-SNAPSHOT:
ndk-build (default-ndk-build) on project native-code: Failure during build: ANDROID-040-001: Could not execute: Command = cmd.exe /X /C "c:\Users\User
\AppData\Local\Android\sdk\ndk-bundle\ndk-build.cmd "APP_ABI=x86 armeabi armeabi-v7a mips" -C D:\workspace\android-ndk-maven-plugin\src\test\projects\
native\native-code NDK_LIBS_OUT=D:\workspace\android-ndk-maven-plugin\src\test\projects\native\native-code\target\ndk-libs NDK_OUT=D:\workspace\androi
d-ndk-maven-plugin\src\test\projects\native\native-code\target\obj V=1 -B all", Result = 2
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failure during build: ANDROID-040-001: Could not execute: Command = cmd.exe /X /C "c:\Users
\User\AppData\Local\Android\sdk\ndk-bundle\ndk-build.cmd "APP_ABI=x86 armeabi armeabi-v7a mips" -C D:\workspace\android-ndk-maven-plugin\src\test\proj
ects\native\native-code NDK_LIBS_OUT=D:\workspace\android-ndk-maven-plugin\src\test\projects\native\native-code\target\ndk-libs NDK_OUT=D:\workspace\a
ndroid-ndk-maven-plugin\src\test\projects\native\native-code\target\obj V=1 -B all", Result = 2
        at com.simpligility.maven.plugins.androidndk.phase05compile.NdkBuildMojo.compile(NdkBuildMojo.java:575)
        at com.simpligility.maven.plugins.androidndk.phase05compile.NdkBuildMojo.execute(NdkBuildMojo.java:397)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.simpligility.maven.plugins.androidndk.ExecutionException: ANDROID-040-001: Could not execute: Command = cmd.exe /X /C "c:\Users\User\Ap
pData\Local\Android\sdk\ndk-bundle\ndk-build.cmd "APP_ABI=x86 armeabi armeabi-v7a mips" -C D:\workspace\android-ndk-maven-plugin\src\test\projects\nat
ive\native-code NDK_LIBS_OUT=D:\workspace\android-ndk-maven-plugin\src\test\projects\native\native-code\target\ndk-libs NDK_OUT=D:\workspace\android-n
dk-maven-plugin\src\test\projects\native\native-code\target\obj V=1 -B all", Result = 2
        at com.simpligility.maven.plugins.androidndk.CommandExecutor$Factory$DefaultCommandExecutor.executeCommand(CommandExecutor.java:249)
        at com.simpligility.maven.plugins.androidndk.phase05compile.NdkBuildMojo.compile(NdkBuildMojo.java:555)
        ... 23 more
```

**Comment by nahojkap** [comment]
The version should be updated when the test runs - what command line did you use?

What NDK is installed here ' c:\Users\User\AppData\Local\Android\sdk\ndk-bundle\ndk-build.cmd' ?

I ask as I can't reproduce this locally.
